//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.23 at 12:59:32 PM GMT+03:00 
//


package com.demo.is550.lms_web_service.generatedSources;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lbs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetStudentRequest_QNAME = new QName("http://lms.com", "GetStudentRequest");
    private final static QName _GetStudentResponse_QNAME = new QName("http://lms.com", "GetStudentResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lbs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStudentRequestType }
     * 
     */
    public GetStudentRequestType createGetStudentRequestType() {
        return new GetStudentRequestType();
    }

    /**
     * Create an instance of {@link GetStudentResponseType }
     * 
     */
    public GetStudentResponseType createGetStudentResponseType() {
        return new GetStudentResponseType();
    }

    /**
     * Create an instance of {@link Student }
     * 
     */
    public Student createStudent() {
        return new Student();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStudentRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStudentRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "GetStudentRequest")
    public JAXBElement<GetStudentRequestType> createGetStudentRequest(GetStudentRequestType value) {
        return new JAXBElement<GetStudentRequestType>(_GetStudentRequest_QNAME, GetStudentRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStudentResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStudentResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "GetStudentResponse")
    public JAXBElement<GetStudentResponseType> createGetStudentResponse(GetStudentResponseType value) {
        return new JAXBElement<GetStudentResponseType>(_GetStudentResponse_QNAME, GetStudentResponseType.class, null, value);
    }

}
