//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.15 at 09:25:41 PM TRT 
//


package com.demo.is550.lms_web_service.generatedSources;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetStudentRequest_QNAME = new QName("http://lms.com", "GetStudentRequest");
    private final static QName _GetStudentResponse_QNAME = new QName("http://lms.com", "GetStudentResponse");
    private final static QName _GetAllBooksRequest_QNAME = new QName("http://lms.com", "GetAllBooksRequest");
    private final static QName _GetAllBooksResponse_QNAME = new QName("http://lms.com", "GetAllBooksResponse");
    private final static QName _GetBookByIdRequest_QNAME = new QName("http://lms.com", "GetBookByIdRequest");
    private final static QName _GetBookByIdResponse_QNAME = new QName("http://lms.com", "GetBookByIdResponse");
    private final static QName _DeleteBookByIdRequest_QNAME = new QName("http://lms.com", "DeleteBookByIdRequest");
    private final static QName _DeleteBookByIdResponse_QNAME = new QName("http://lms.com", "DeleteBookByIdResponse");
    private final static QName _AddBookRequest_QNAME = new QName("http://lms.com", "AddBookRequest");
    private final static QName _AddBookResponse_QNAME = new QName("http://lms.com", "AddBookResponse");
    private final static QName _UpdateBookRequest_QNAME = new QName("http://lms.com", "UpdateBookRequest");
    private final static QName _UpdateBookResponse_QNAME = new QName("http://lms.com", "UpdateBookResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStudentRequestType }
     * 
     */
    public GetStudentRequestType createGetStudentRequestType() {
        return new GetStudentRequestType();
    }

    /**
     * Create an instance of {@link GetStudentResponseType }
     * 
     */
    public GetStudentResponseType createGetStudentResponseType() {
        return new GetStudentResponseType();
    }

    /**
     * Create an instance of {@link GetAllBooksRequestType }
     * 
     */
    public GetAllBooksRequestType createGetAllBooksRequestType() {
        return new GetAllBooksRequestType();
    }

    /**
     * Create an instance of {@link GetAllBooksResponseType }
     * 
     */
    public GetAllBooksResponseType createGetAllBooksResponseType() {
        return new GetAllBooksResponseType();
    }

    /**
     * Create an instance of {@link GetBookByIdRequestType }
     * 
     */
    public GetBookByIdRequestType createGetBookByIdRequestType() {
        return new GetBookByIdRequestType();
    }

    /**
     * Create an instance of {@link GetBookByIdResponseType }
     * 
     */
    public GetBookByIdResponseType createGetBookByIdResponseType() {
        return new GetBookByIdResponseType();
    }

    /**
     * Create an instance of {@link DeleteBookByIdRequestType }
     * 
     */
    public DeleteBookByIdRequestType createDeleteBookByIdRequestType() {
        return new DeleteBookByIdRequestType();
    }

    /**
     * Create an instance of {@link DeleteBookByIdResponseType }
     * 
     */
    public DeleteBookByIdResponseType createDeleteBookByIdResponseType() {
        return new DeleteBookByIdResponseType();
    }

    /**
     * Create an instance of {@link AddBookRequestType }
     * 
     */
    public AddBookRequestType createAddBookRequestType() {
        return new AddBookRequestType();
    }

    /**
     * Create an instance of {@link AddBookResponseType }
     * 
     */
    public AddBookResponseType createAddBookResponseType() {
        return new AddBookResponseType();
    }

    /**
     * Create an instance of {@link UpdateBookRequestType }
     * 
     */
    public UpdateBookRequestType createUpdateBookRequestType() {
        return new UpdateBookRequestType();
    }

    /**
     * Create an instance of {@link UpdateBookResponseType }
     * 
     */
    public UpdateBookResponseType createUpdateBookResponseType() {
        return new UpdateBookResponseType();
    }

    /**
     * Create an instance of {@link Student }
     * 
     */
    public Student createStudent() {
        return new Student();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStudentRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStudentRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "GetStudentRequest")
    public JAXBElement<GetStudentRequestType> createGetStudentRequest(GetStudentRequestType value) {
        return new JAXBElement<GetStudentRequestType>(_GetStudentRequest_QNAME, GetStudentRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStudentResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetStudentResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "GetStudentResponse")
    public JAXBElement<GetStudentResponseType> createGetStudentResponse(GetStudentResponseType value) {
        return new JAXBElement<GetStudentResponseType>(_GetStudentResponse_QNAME, GetStudentResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllBooksRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAllBooksRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "GetAllBooksRequest")
    public JAXBElement<GetAllBooksRequestType> createGetAllBooksRequest(GetAllBooksRequestType value) {
        return new JAXBElement<GetAllBooksRequestType>(_GetAllBooksRequest_QNAME, GetAllBooksRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllBooksResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetAllBooksResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "GetAllBooksResponse")
    public JAXBElement<GetAllBooksResponseType> createGetAllBooksResponse(GetAllBooksResponseType value) {
        return new JAXBElement<GetAllBooksResponseType>(_GetAllBooksResponse_QNAME, GetAllBooksResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBookByIdRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetBookByIdRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "GetBookByIdRequest")
    public JAXBElement<GetBookByIdRequestType> createGetBookByIdRequest(GetBookByIdRequestType value) {
        return new JAXBElement<GetBookByIdRequestType>(_GetBookByIdRequest_QNAME, GetBookByIdRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetBookByIdResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetBookByIdResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "GetBookByIdResponse")
    public JAXBElement<GetBookByIdResponseType> createGetBookByIdResponse(GetBookByIdResponseType value) {
        return new JAXBElement<GetBookByIdResponseType>(_GetBookByIdResponse_QNAME, GetBookByIdResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteBookByIdRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeleteBookByIdRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "DeleteBookByIdRequest")
    public JAXBElement<DeleteBookByIdRequestType> createDeleteBookByIdRequest(DeleteBookByIdRequestType value) {
        return new JAXBElement<DeleteBookByIdRequestType>(_DeleteBookByIdRequest_QNAME, DeleteBookByIdRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteBookByIdResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeleteBookByIdResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "DeleteBookByIdResponse")
    public JAXBElement<DeleteBookByIdResponseType> createDeleteBookByIdResponse(DeleteBookByIdResponseType value) {
        return new JAXBElement<DeleteBookByIdResponseType>(_DeleteBookByIdResponse_QNAME, DeleteBookByIdResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddBookRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddBookRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "AddBookRequest")
    public JAXBElement<AddBookRequestType> createAddBookRequest(AddBookRequestType value) {
        return new JAXBElement<AddBookRequestType>(_AddBookRequest_QNAME, AddBookRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddBookResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AddBookResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "AddBookResponse")
    public JAXBElement<AddBookResponseType> createAddBookResponse(AddBookResponseType value) {
        return new JAXBElement<AddBookResponseType>(_AddBookResponse_QNAME, AddBookResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateBookRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateBookRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "UpdateBookRequest")
    public JAXBElement<UpdateBookRequestType> createUpdateBookRequest(UpdateBookRequestType value) {
        return new JAXBElement<UpdateBookRequestType>(_UpdateBookRequest_QNAME, UpdateBookRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateBookResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateBookResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://lms.com", name = "UpdateBookResponse")
    public JAXBElement<UpdateBookResponseType> createUpdateBookResponse(UpdateBookResponseType value) {
        return new JAXBElement<UpdateBookResponseType>(_UpdateBookResponse_QNAME, UpdateBookResponseType.class, null, value);
    }

}
